version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-node-browsers
    working_directory: ~/repos
    steps:
      - checkout
      - run:
          name: install bundler
          command: gem install bundler -v '<2'
      - run:
          name: install dependencies
          command: bundle install
      - run:
          name: run RuboCop
          command: bundle exec rubocop
      - run:
          name: bundle check
          command: bundle check
      - run:
          name: update cert
          command: bundle exec rake cert:update
      - run:
          name: check fresh
          command: bundle exec bin/check_fresh_gems.rb
