package:
  authors:
    - Tatsuya Koishi
  description: ginseng PostgreSQL libraries
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/ginseng-postgres
  version: 1.3.15
postgres:
  dsn: postgres://postgres:password@localhost:5432/test
  slow_query:
    seconds: 5
