name: test
on:
  - push
env:
  CI: "true"
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.7
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: apt install
        run: |
          sudo apt install libpq-dev
      - name: bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake bundle:update
          bundle exec rake bundle:check
      - name: Run lint
        run: |
          bundle exec rubocop
      - name: Run test
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PORT: 5432
        run: |
          bundle exec rake test
