name: test
on:
  - push
env:
  CI: "true"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    container: ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - ruby:2.6
          - ruby:2.7
          - ruby:3.0
    steps:
      - uses: actions/checkout@v2
      - name: apt install
        run: |
          sudo apt update
          sudo apt install libpq-dev
      - name: bundle install
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rake bundle:update
          bundle exec rake bundle:check
      - name: Run lint
        run: |
          bundle exec rubocop
      - name: Run test
        run: |
          bundle exec rake test
